// Generated by scripts/gen-asset-meta.py - do not edit.
.pragma library

var assets = {
  "goblin": {
    "verts": 10906,
    "tris": 9964,
    "skeleton": "",
    "bones": 62,
    "name": "Goblin",
    "source": "assets/source-images/Goblin.png",
    "exported": "assets/exported/Goblin/Goblin.glb",
    "runtime": "assets/runtime/goblin/Goblin.qml",
    "textures": [
      "qtmesh_gen3d_2_1788575330441_diffuse.png",
      "qtmesh_gen3d_2_1788575330441_normal.png",
      "qtmesh_gen3d_2_1788575330441_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Gather",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Goblin/Goblin_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "orc": {
    "verts": 10623,
    "tris": 9952,
    "skeleton": "",
    "bones": 20,
    "name": "Orc",
    "source": "assets/source-images/Orc.png",
    "exported": "assets/exported/Orc/Orc.glb",
    "runtime": "assets/runtime/orc/Orc.qml",
    "textures": [
      "qtmesh_gen3d_1_1788482829942_diffuse.png",
      "qtmesh_gen3d_1_1788482829942_normal.png",
      "qtmesh_gen3d_1_1788482829942_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Orc/Orc_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "orc_archer": {
    "verts": 10539,
    "tris": 9918,
    "skeleton": "",
    "bones": 64,
    "name": "Orc Archer",
    "source": "assets/source-images/Orc Archer.png",
    "exported": "assets/exported/Orc Archer/Orc Archer.glb",
    "runtime": "assets/runtime/orc_archer/OrcArcher.qml",
    "textures": [
      "qtmesh_gen3d_3_1788580202226_diffuse.png",
      "qtmesh_gen3d_3_1788580202226_normal.png",
      "qtmesh_gen3d_3_1788580202226_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Orc Archer/Orc Archer_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "ogre": {
    "verts": 10657,
    "tris": 9908,
    "skeleton": "",
    "bones": 20,
    "name": "Ogre",
    "source": "assets/source-images/Ogre.png",
    "exported": "assets/exported/Ogre/Ogre.glb",
    "runtime": "assets/runtime/ogre/Ogre.qml",
    "textures": [
      "qtmesh_gen3d_1_1788480558057_diffuse.png",
      "qtmesh_gen3d_1_1788480558057_normal.png",
      "qtmesh_gen3d_1_1788480558057_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Ogre/Ogre_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "clan_fortress": {
    "verts": 15926,
    "tris": 9788,
    "skeleton": "",
    "bones": 0,
    "name": "Clan Fortress",
    "source": "assets/source-images/Clan Fortress.png",
    "exported": "assets/exported/Clan Fortress/Clan Fortress.glb",
    "runtime": "assets/runtime/clan_fortress/ClanFortress.qml",
    "textures": [
      "qtmesh_gen3d_1_1788478725222_diffuse.png",
      "qtmesh_gen3d_1_1788478725222_normal.png",
      "qtmesh_gen3d_1_1788478725222_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "war_foundry": {
    "verts": 15331,
    "tris": 9918,
    "skeleton": "",
    "bones": 0,
    "name": "War Foundry",
    "source": "assets/source-images/War Foundry.png",
    "exported": "assets/exported/War Foundry/War Foundry.glb",
    "runtime": "assets/runtime/war_foundry/WarFoundry.qml",
    "textures": [
      "qtmesh_gen3d_1_1788485235370_diffuse.png",
      "qtmesh_gen3d_1_1788485235370_normal.png",
      "qtmesh_gen3d_1_1788485235370_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "iron_deposit": {
    "verts": 11554,
    "tris": 9994,
    "skeleton": "",
    "bones": 0,
    "name": "Iron Deposit",
    "source": "assets/source-images/Iron Deposit.png",
    "exported": "assets/exported/Iron Deposit/Iron Deposit.glb",
    "runtime": "assets/runtime/iron_deposit/IronDeposit.qml",
    "textures": [
      "qtmesh_gen3d_1_1788479538976_diffuse.png",
      "qtmesh_gen3d_1_1788479538976_normal.png",
      "qtmesh_gen3d_1_1788479538976_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "large_rocks": {
    "verts": 8988,
    "tris": 9998,
    "skeleton": "",
    "bones": 0,
    "name": "Large Rocks",
    "source": "assets/source-images/Large Rocks.png",
    "exported": "assets/exported/Large Rocks/Large Rocks.glb",
    "runtime": "assets/runtime/large_rocks/LargeRocks.qml",
    "textures": [
      "qtmesh_gen3d_1_1788480093803_diffuse.png",
      "qtmesh_gen3d_1_1788480093803_normal.png",
      "qtmesh_gen3d_1_1788480093803_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "small_rocks": {
    "verts": 8453,
    "tris": 9990,
    "skeleton": "",
    "bones": 0,
    "name": "Small Rocks",
    "source": "assets/source-images/Small Rocks.png",
    "exported": "assets/exported/Small Rocks/Small Rocks.glb",
    "runtime": "assets/runtime/small_rocks/SmallRocks.qml",
    "textures": [
      "qtmesh_gen3d_1_1788484933545_diffuse.png",
      "qtmesh_gen3d_1_1788484933545_normal.png",
      "qtmesh_gen3d_1_1788484933545_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "dead_tree": {
    "verts": 12859,
    "tris": 9058,
    "skeleton": "",
    "bones": 0,
    "name": "Dead Ironwood tree",
    "source": "assets/source-images/Dead Ironwood tree.png",
    "exported": "assets/exported/Dead Ironwood tree/Dead Ironwood tree.glb",
    "runtime": "assets/runtime/dead_tree/DeadIronwoodtree.qml",
    "textures": [
      "qtmesh_gen3d_1_1788478991592_diffuse.png",
      "qtmesh_gen3d_1_1788478991592_normal.png",
      "qtmesh_gen3d_1_1788478991592_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "broken_cart": {
    "verts": 13482,
    "tris": 9866,
    "skeleton": "",
    "bones": 0,
    "name": "Broken Cart",
    "source": "assets/source-images/Broken Cart.png",
    "exported": "assets/exported/Broken Cart/Broken Cart.glb",
    "runtime": "assets/runtime/broken_cart/BrokenCart.qml",
    "textures": [
      "qtmesh_gen3d_1_1788478215302_diffuse.png",
      "qtmesh_gen3d_1_1788478215302_normal.png",
      "qtmesh_gen3d_1_1788478215302_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "arrow": {
    "verts": 8784,
    "tris": 10000,
    "skeleton": "",
    "bones": 0,
    "name": "Arrow",
    "source": "assets/source-images/Arrow.png",
    "exported": "assets/exported/Arrow/Arrow.glb",
    "runtime": "assets/runtime/arrow/Arrow.qml",
    "textures": [
      "qtmesh_gen3d_1_1788476954751_diffuse.png",
      "qtmesh_gen3d_1_1788476954751_normal.png",
      "qtmesh_gen3d_1_1788476954751_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  }
}
