// Generated by scripts/gen-asset-meta.py - do not edit.
.pragma library

var assets = {
  "goblin": {
    "verts": 10906,
    "tris": 9964,
    "skeleton": "",
    "bones": 62,
    "name": "Goblin",
    "source": "assets/source-images/Goblin.png",
    "exported": "assets/exported/Goblin/Goblin.glb",
    "runtime": "assets/runtime/goblin/Goblin.qml",
    "textures": [
      "qtmesh_gen3d_2_1788575330441_diffuse.png",
      "qtmesh_gen3d_2_1788575330441_normal.png",
      "qtmesh_gen3d_2_1788575330441_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Gather",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Goblin/Goblin_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "orc": {
    "verts": 11043,
    "tris": 9910,
    "skeleton": "",
    "bones": 20,
    "name": "Orc",
    "source": "assets/source-images/Orc.png",
    "exported": "assets/exported/Orc/Orc.glb",
    "runtime": "assets/runtime/orc/Orc.qml",
    "textures": [
      "qtmesh_gen3d_1_1788603671564_diffuse.png",
      "qtmesh_gen3d_1_1788603671564_normal.png",
      "qtmesh_gen3d_1_1788603671564_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Orc/Orc_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "orc_archer": {
    "verts": 10539,
    "tris": 9918,
    "skeleton": "",
    "bones": 64,
    "name": "Orc Archer",
    "source": "assets/source-images/Orc Archer.png",
    "exported": "assets/exported/Orc Archer/Orc Archer.glb",
    "runtime": "assets/runtime/orc_archer/OrcArcher.qml",
    "textures": [
      "qtmesh_gen3d_3_1788580202226_diffuse.png",
      "qtmesh_gen3d_3_1788580202226_normal.png",
      "qtmesh_gen3d_3_1788580202226_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Orc Archer/Orc Archer_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "ogre": {
    "verts": 11292,
    "tris": 9852,
    "skeleton": "",
    "bones": 20,
    "name": "Ogre",
    "source": "assets/source-images/Ogre.png",
    "exported": "assets/exported/Ogre/Ogre.glb",
    "runtime": "assets/runtime/ogre/Ogre.qml",
    "textures": [
      "qtmesh_gen3d_1_1788603161353_diffuse.png",
      "qtmesh_gen3d_1_1788603161353_normal.png",
      "qtmesh_gen3d_1_1788603161353_roughness.png"
    ],
    "clips": [
      "Attack",
      "Death",
      "Hit",
      "Idle",
      "Walk"
    ],
    "rigged": "assets/rigged/Ogre/Ogre_rigged.glb",
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML + .qad clips",
    "status": "QtMeshEditor-generated"
  },
  "clan_fortress": {
    "verts": 15554,
    "tris": 9828,
    "skeleton": "",
    "bones": 0,
    "name": "Clan Fortress",
    "source": "assets/source-images/Clan Fortress.png",
    "exported": "assets/exported/Clan Fortress/Clan Fortress.glb",
    "runtime": "assets/runtime/clan_fortress/ClanFortress.qml",
    "textures": [
      "qtmesh_gen3d_1_1788604320591_diffuse.png",
      "qtmesh_gen3d_1_1788604320591_normal.png",
      "qtmesh_gen3d_1_1788604320591_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "war_foundry": {
    "verts": 14664,
    "tris": 9930,
    "skeleton": "",
    "bones": 0,
    "name": "War Foundry",
    "source": "assets/source-images/War Foundry.png",
    "exported": "assets/exported/War Foundry/War Foundry.glb",
    "runtime": "assets/runtime/war_foundry/WarFoundry.qml",
    "textures": [
      "qtmesh_gen3d_1_1788604883446_diffuse.png",
      "qtmesh_gen3d_1_1788604883446_normal.png",
      "qtmesh_gen3d_1_1788604883446_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "iron_deposit": {
    "verts": 12867,
    "tris": 9998,
    "skeleton": "",
    "bones": 0,
    "name": "Iron Deposit",
    "source": "assets/source-images/Iron Deposit.png",
    "exported": "assets/exported/Iron Deposit/Iron Deposit.glb",
    "runtime": "assets/runtime/iron_deposit/IronDeposit.qml",
    "textures": [
      "qtmesh_gen3d_1_1788606390803_diffuse.png",
      "qtmesh_gen3d_1_1788606390803_normal.png",
      "qtmesh_gen3d_1_1788606390803_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "large_rocks": {
    "verts": 12844,
    "tris": 9842,
    "skeleton": "",
    "bones": 0,
    "name": "Large Rocks",
    "source": "assets/source-images/Large Rocks.png",
    "exported": "assets/exported/Large Rocks/Large Rocks.glb",
    "runtime": "assets/runtime/large_rocks/LargeRocks.qml",
    "textures": [
      "qtmesh_gen3d_1_1788607383666_diffuse.png",
      "qtmesh_gen3d_1_1788607383666_normal.png",
      "qtmesh_gen3d_1_1788607383666_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "small_rocks": {
    "verts": 10963,
    "tris": 9920,
    "skeleton": "",
    "bones": 0,
    "name": "Small Rocks",
    "source": "assets/source-images/Small Rocks.png",
    "exported": "assets/exported/Small Rocks/Small Rocks.glb",
    "runtime": "assets/runtime/small_rocks/SmallRocks.qml",
    "textures": [
      "qtmesh_gen3d_1_1788607997570_diffuse.png",
      "qtmesh_gen3d_1_1788607997570_normal.png",
      "qtmesh_gen3d_1_1788607997570_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "dead_tree": {
    "verts": 10380,
    "tris": 9955,
    "skeleton": "",
    "bones": 0,
    "name": "Dead Ironwood tree",
    "source": "assets/source-images/Dead Ironwood tree.png",
    "exported": "assets/exported/Dead Ironwood tree/Dead Ironwood tree.glb",
    "runtime": "assets/runtime/dead_tree/DeadIronwoodtree.qml",
    "textures": [
      "qtmesh_gen3d_1_1788608453576_diffuse.png",
      "qtmesh_gen3d_1_1788608453576_normal.png",
      "qtmesh_gen3d_1_1788608453576_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "broken_cart": {
    "verts": 13660,
    "tris": 9906,
    "skeleton": "",
    "bones": 0,
    "name": "Broken Cart",
    "source": "assets/source-images/Broken Cart.png",
    "exported": "assets/exported/Broken Cart/Broken Cart.glb",
    "runtime": "assets/runtime/broken_cart/BrokenCart.qml",
    "textures": [
      "qtmesh_gen3d_1_1788609127455_diffuse.png",
      "qtmesh_gen3d_1_1788609127455_normal.png",
      "qtmesh_gen3d_1_1788609127455_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "arrow": {
    "verts": 8366,
    "tris": 9990,
    "skeleton": "",
    "bones": 0,
    "name": "Arrow",
    "source": "assets/source-images/Arrow.png",
    "exported": "assets/exported/Arrow/Arrow.glb",
    "runtime": "assets/runtime/arrow/Arrow.qml",
    "textures": [
      "qtmesh_gen3d_1_1788609456452_diffuse.png",
      "qtmesh_gen3d_1_1788609456452_normal.png",
      "qtmesh_gen3d_1_1788609456452_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "bloodmaw_outpost": {
    "verts": 15533,
    "tris": 9940,
    "skeleton": "",
    "bones": 0,
    "name": "Bloodmaw Outpost",
    "source": "assets/source-images/Bloodmaw Outpost.png",
    "exported": "assets/exported/Bloodmaw Outpost/Bloodmaw Outpost.glb",
    "runtime": "assets/runtime/bloodmaw_outpost/BloodmawOutpost.qml",
    "textures": [
      "qtmesh_gen3d_1_1788762287542_diffuse.png",
      "qtmesh_gen3d_1_1788762287542_normal.png",
      "qtmesh_gen3d_1_1788762287542_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "bloodmaw_fortress": {
    "verts": 16359,
    "tris": 9758,
    "skeleton": "",
    "bones": 0,
    "name": "Bloodmaw Fortress",
    "source": "assets/source-images/Bloodmaw Fortress.png",
    "exported": "assets/exported/Bloodmaw Fortress/Bloodmaw Fortress.glb",
    "runtime": "assets/runtime/bloodmaw_fortress/BloodmawFortress.qml",
    "textures": [
      "qtmesh_gen3d_1_1788764606997_diffuse.png",
      "qtmesh_gen3d_1_1788764606997_normal.png",
      "qtmesh_gen3d_1_1788764606997_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "watchtower": {
    "verts": 14138,
    "tris": 9998,
    "skeleton": "",
    "bones": 0,
    "name": "Watchtower",
    "source": "assets/source-images/Watchtower.png",
    "exported": "assets/exported/Watchtower/Watchtower.glb",
    "runtime": "assets/runtime/watchtower/Watchtower.qml",
    "textures": [
      "qtmesh_gen3d_1_1788762603858_diffuse.png",
      "qtmesh_gen3d_1_1788762603858_normal.png",
      "qtmesh_gen3d_1_1788762603858_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "gate": {
    "verts": 11420,
    "tris": 10000,
    "skeleton": "",
    "bones": 0,
    "name": "Bloodmaw Gate",
    "source": "assets/source-images/Bloodmaw Gate.png",
    "exported": "assets/exported/Bloodmaw Gate/Bloodmaw Gate.glb",
    "runtime": "assets/runtime/gate/BloodmawGate.qml",
    "textures": [
      "qtmesh_gen3d_1_1788762833035_diffuse.png",
      "qtmesh_gen3d_1_1788762833035_normal.png",
      "qtmesh_gen3d_1_1788762833035_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "prisoner_cage": {
    "verts": 12751,
    "tris": 9972,
    "skeleton": "",
    "bones": 0,
    "name": "Prisoner Cage",
    "source": "assets/source-images/Prisoner Cage.png",
    "exported": "assets/exported/Prisoner Cage/Prisoner Cage.glb",
    "runtime": "assets/runtime/prisoner_cage/PrisonerCage.qml",
    "textures": [
      "qtmesh_gen3d_1_1788763477028_diffuse.png",
      "qtmesh_gen3d_1_1788763477028_normal.png",
      "qtmesh_gen3d_1_1788763477028_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "steam_vent": {
    "verts": 13840,
    "tris": 9760,
    "skeleton": "",
    "bones": 0,
    "name": "Steam Vent",
    "source": "assets/source-images/Steam Vent.png",
    "exported": "assets/exported/Steam Vent/Steam Vent.glb",
    "runtime": "assets/runtime/steam_vent/SteamVent.qml",
    "textures": [
      "qtmesh_gen3d_1_1788763847895_diffuse.png",
      "qtmesh_gen3d_1_1788763847895_normal.png",
      "qtmesh_gen3d_1_1788763847895_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "ruined_foundry": {
    "verts": 15983,
    "tris": 9802,
    "skeleton": "",
    "bones": 0,
    "name": "Ruined Foundry",
    "source": "assets/source-images/Ruined Foundry.png",
    "exported": "assets/exported/Ruined Foundry/Ruined Foundry.glb",
    "runtime": "assets/runtime/ruined_foundry/RuinedFoundry.qml",
    "textures": [
      "qtmesh_gen3d_1_1788764215166_diffuse.png",
      "qtmesh_gen3d_1_1788764215166_normal.png",
      "qtmesh_gen3d_1_1788764215166_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  },
  "iron_crown": {
    "verts": 11952,
    "tris": 9906,
    "skeleton": "",
    "bones": 0,
    "name": "Iron Crown",
    "source": "assets/source-images/Iron Crown.png",
    "exported": "assets/exported/Iron Crown/Iron Crown.glb",
    "runtime": "assets/runtime/iron_crown/IronCrown.qml",
    "textures": [
      "qtmesh_gen3d_1_1788764881892_diffuse.png",
      "qtmesh_gen3d_1_1788764881892_normal.png",
      "qtmesh_gen3d_1_1788764881892_roughness.png"
    ],
    "clips": [],
    "format": "GLB (QtMeshEditor) → balsam .mesh + QML",
    "status": "QtMeshEditor-generated"
  }
}
