#!/usr/bin/env python3
"""Regenerate docs/asset-manifest.md from the assets on disk (qtmesh info + runtime folders).

    python3 scripts/gen-asset-manifest.py

Data-driven so the manifest cannot drift from the files: triangles/vertices from the exported
GLBs, skeleton/clips from the rigged GLBs, runtime status from assets/runtime, QtMeshEditor
version from the CLI.
"""
import glob
import os
import re
import subprocess
from datetime import date

Q = os.environ.get("QTMESH", "/opt/homebrew/bin/qtmesheditor")
ENV = dict(os.environ, QTMESH_NO_TELEMETRY="1")

UNITS = [("Goblin", "goblin", "Goblin Worker"), ("Orc", "orc", "Orc Warrior"),
         ("Orc Archer", "orc_archer", "Orc Archer"), ("Ogre", "ogre", "Ironhide Ogre")]
BUILDINGS = [("Clan Fortress", "clan_fortress", "Clan Fortress (and Enemy Fortress, rotated)"),
             ("War Foundry", "war_foundry", "War Foundry"), ("Iron Deposit", "iron_deposit", "Iron Deposit"),
             ("Anvil", None, "foundry prop"), ("Fire", None, "foundry/camp prop"), ("Weapons", None, "weapon rack prop"),
             ("Clan Banner", None, "fortress decoration"), ("Ironfang emblem", None, "menu / HUD"),
             ("Ironfang", None, "title / logo prop"), ("Broken Cart", "broken_cart", "map obstacle"),
             ("Dead Ironwood tree", "dead_tree", "map obstacle"), ("Large Rocks", "large_rocks", "map obstacle"),
             ("Small Rocks", "small_rocks", "map decoration"), ("Basket", None, "prop")]
WEAPONS = [("Arrow", "arrow", "archer projectile"), ("Bow", None, ""), ("Cleaver", None, ""),
           ("Hammer", None, ""), ("Pickaxe", None, "worker tool"), ("Shield", None, "")]


def info(path):
    out = subprocess.run([Q, "info", path], capture_output=True, text=True, env=ENV).stdout
    g = lambda k: re.search(rf"^{k}:\s*(.+)$", out, re.M)
    d = {"verts": 0, "tris": 0, "bones": 0}
    for key, name in (("Vertices", "verts"), ("Triangles", "tris")):
        m = g(key); d[name] = int(m.group(1)) if m else 0
    m = re.search(r"\((\d+) bones\)", out); d["bones"] = int(m.group(1)) if m else 0
    return d


def clips(name):
    rig = f"assets/rigged/{name}/{name}_rigged.glb"
    if not os.path.exists(rig):
        return "", 0
    out = subprocess.run([Q, "anim", rig, "--list"], capture_output=True, text=True, env=ENV).stdout
    found = re.findall(r"^\s{2}(\w+)\s+([\d.]+)s", out, re.M)
    return " · ".join(f"{n} {float(t):.1f} s" for n, t in found), info(rig)["bones"]


def n(v): return f"{v:,}".replace(",", " ")


def row_status(runtime_folder):
    if runtime_folder and os.path.isdir(f"assets/runtime/{runtime_folder}"):
        return f"**runtime** (`assets/runtime/{runtime_folder}/`)"
    return "static"


def main():
    version = subprocess.run([Q, "--version"], capture_output=True, text=True, env=ENV).stdout.strip() or "qtmesh"
    lines = [f"# Asset manifest", "",
             f"Generated by `scripts/gen-asset-manifest.py` on {date.today().isoformat()} from the files on disk. "
             f"Models are produced with **{version}** (TRELLIS.2 backend) using the recipe in `docs/asset-pipeline.md`; "
             "source images are original concept art for this project (`assets/source-images/`).", "",
             "Legend — **Status**: `static` = TRELLIS.2 GLB only · `runtime` = balsam-imported and used by the app. "
             "The Enemy Fortress reuses the Clan Fortress model (rotated 180°, red team frame). Audio is synthesized by "
             "`scripts/gen-audio.py` (17 WAVs, original). Machine-readable metadata for the in-game showcase: "
             "`app/config/assetmeta.js` (`scripts/gen-asset-meta.py`).", "",
             "## Units", "",
             "| Asset | Source image | Tris | Verts | Textures | Skeleton | Clips | Status | Game type |",
             "|---|---|---:|---:|---|---|---|---|---|"]
    for name, folder, game in UNITS:
        glb = f"assets/exported/{name}/{name}.glb"
        if not os.path.exists(glb):
            lines.append(f"| {name} | {name}.png | — | — | — | — | — | *not generated* | {game} |"); continue
        d = info(glb); c, bones = clips(name)
        tex = len(glob.glob(f"assets/runtime/{folder}/maps/*")) if folder else 4
        lines.append(f"| {name} | {name}.png | {n(d['tris'])} | {n(d['verts'])} | {tex} × 1024² PNG | "
                     f"{(str(bones) + '-bone humanoid (qtmesh rig)') if bones else '—'} | {c or '—'} | {row_status(folder)} | {game} |")
    lines += ["", "## Buildings and props", "",
              "| Asset | Source image | Tris | Verts | Status | Intended use |", "|---|---|---:|---:|---|---|"]
    for name, folder, use in BUILDINGS:
        glb = f"assets/exported/{name}/{name}.glb"
        if not os.path.exists(glb):
            lines.append(f"| {name} | {name}.png | — | — | *not generated* | {use} |"); continue
        d = info(glb)
        lines.append(f"| {name} | {name}.png | {n(d['tris'])} | {n(d['verts'])} | {row_status(folder)} | {use} |")
    lines += ["", "## Weapons (hand-held, attach later)", "",
              "| Asset | Source image | Tris | Verts | Status |", "|---|---|---:|---:|---|"]
    for name, folder, use in WEAPONS:
        glb = f"assets/exported/{name}/{name}.glb"
        if not os.path.exists(glb):
            lines.append(f"| {name} | {name}.png | — | — | *not generated* |"); continue
        d = info(glb)
        st = row_status(folder) + (f", {use}" if use else "")
        lines.append(f"| {name} | {name}.png | {n(d['tris'])} | {n(d['verts'])} | {st} |")
    lines += ["", "## Common properties", "",
              "| Property | Value |", "|---|---|",
              "| Export format | glTF 2.0 binary (`.glb`), textures external PNG |",
              "| Runtime format | balsam `.mesh` + `.qad` keyframes + QML (Qt 6.11) |",
              "| Coordinate system | Y up, right-handed, metres after `scale` (`app/config/assets.js`) |",
              "| Bounding box | normalised to ≈1 unit, centred at origin (TRELLIS.2); `footOffset` = distance from origin to the base |",
              "| Texture maps | `*_diffuse` (base color RGBA), `*_normal` (tangent), `*_roughness`, `*_metallic` — 1024×1024 PNG |",
              "| Material naming | `qtmesh_gen3d_<n>_<timestamp>_mesh_mat` (QtMeshEditor generated) |",
              "| Collision | none in 3D; navigation uses `NavGrid.blockRect` footprints (1 m cells) |",
              "| LOD | none yet (`qtmesh lod --algo meshopt` available) |",
              "| Validation | `qtmesh validate <glb>`; turntable renders `assets/exported/<Name>/<Name>_turntable.png` |",
              "| License | generated assets: project MIT; motion clips: see `THIRD_PARTY_LICENSES.md` |", "",
              "Regenerate a turntable: `qtmesh turntable assets/exported/<Name>/<Name>.glb -o <Name>_turntable.png --frames 8 --size 512x512`.", ""]
    open("docs/asset-manifest.md", "w", encoding="utf-8").write("\n".join(lines))
    print("wrote docs/asset-manifest.md")


if __name__ == "__main__":
    main()
