#!/usr/bin/env python3
"""Write app/config/assetmeta.js: per-asset metadata for the in-game Asset Showcase.

Reads the exported/rigged GLBs with `qtmesh info` (triangles, vertices, bones, animations) and
the runtime folders (clip names from the patched QML, texture files). Re-run after changing
assets. Pure data - the showcase never touches the tools at runtime.
"""
import glob
import json
import os
import re
import subprocess

Q = os.environ.get("QTMESH", "/opt/homebrew/bin/qtmesheditor")
ENV = dict(os.environ, QTMESH_NO_TELEMETRY="1")

RUNTIME = {  # runtime folder -> (exported name, rigged glb or None)
    "goblin": ("Goblin", "assets/rigged/Goblin/Goblin_rigged.glb"),
    "orc": ("Orc", "assets/rigged/Orc/Orc_rigged.glb"),
    "orc_archer": ("Orc Archer", "assets/rigged/Orc Archer/Orc Archer_rigged.glb"),
    "ogre": ("Ogre", "assets/rigged/Ogre/Ogre_rigged.glb"),
    "clan_fortress": ("Clan Fortress", None), "war_foundry": ("War Foundry", None),
    "iron_deposit": ("Iron Deposit", None), "large_rocks": ("Large Rocks", None),
    "small_rocks": ("Small Rocks", None), "dead_tree": ("Dead Ironwood tree", None),
    "broken_cart": ("Broken Cart", None), "arrow": ("Arrow", None),
}


def info(path):
    out = subprocess.run([Q, "info", path], capture_output=True, text=True, env=ENV).stdout
    g = lambda key: re.search(rf"^{key}:\s*(.+)$", out, re.M)
    d = {}
    for key, name in (("Vertices", "verts"), ("Triangles", "tris")):
        m = g(key); d[name] = int(m.group(1)) if m else 0
    m = g("Skeleton"); d["skeleton"] = m.group(1).strip() if m else ""
    m = re.search(r"\((\d+) bones\)", out); d["bones"] = int(m.group(1)) if m else 0
    return d


def main():
    meta = {}
    for folder, (name, rigged) in RUNTIME.items():
        exported = f"assets/exported/{name}/{name}.glb"
        if not os.path.exists(exported):
            continue
        d = info(exported)
        d["name"] = name
        d["source"] = f"assets/source-images/{name}.png"
        d["exported"] = exported
        d["runtime"] = f"assets/runtime/{folder}/{name.replace(' ', '')}.qml"
        d["textures"] = sorted(os.path.basename(p) for p in glob.glob(f"assets/runtime/{folder}/maps/*"))
        qml = open(d["runtime"], encoding="utf-8").read() if os.path.exists(d["runtime"]) else ""
        m = re.search(r"readonly property var clips: \[(.*?)\]", qml)
        d["clips"] = [c.strip().strip('"') for c in m.group(1).split(",") if c.strip()] if m else []
        if rigged and os.path.exists(rigged):
            r = info(rigged); d["bones"] = r["bones"]; d["rigged"] = rigged
        d["format"] = "GLB (QtMeshEditor) → balsam .mesh + QML" + (" + .qad clips" if d["clips"] else "")
        d["status"] = "QtMeshEditor-generated"
        meta[folder] = d
    body = "// Generated by scripts/gen-asset-meta.py - do not edit.\n.pragma library\n\nvar assets = " + \
           json.dumps(meta, indent=2, ensure_ascii=False) + "\n"
    os.makedirs("app/config", exist_ok=True)
    open("app/config/assetmeta.js", "w", encoding="utf-8").write(body)
    print(f"wrote app/config/assetmeta.js ({len(meta)} assets)")


if __name__ == "__main__":
    main()
